{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.emacs.decknix.http;
in
{
  options.programs.emacs.decknix.http = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Enable HTTP/REST client support for API development and testing.
        Provides an interactive REST client with org-babel integration.
      '';
    };

    jq.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable jq integration for parsing JSON responses.";
    };

    orgBabel.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable org-babel support for REST blocks in org files.";
    };
  };

  config = mkIf cfg.enable {
    # Install jq for JSON processing
    home.packages = with pkgs;
      (optionals cfg.jq.enable [ jq ]);

    programs.emacs = {
      extraPackages = epkgs: with epkgs;
        [ restclient ]
        ++ (optionals cfg.jq.enable [ jq-mode restclient-jq ])
        ++ (optionals cfg.orgBabel.enable [ ob-restclient ]);

      extraConfig = ''
        ;;; HTTP/REST Client Configuration
        ;;; Generated by decknix - provides REST API testing capabilities

        ;; == Restclient: Interactive REST client ==
        (use-package restclient
          :mode ("\\.http\\'" . restclient-mode)
          :config
          ;; Keybindings
          ;; C-c C-c - Send request at point
          ;; C-c C-r - Send request and stay in buffer
          ;; C-c C-v - View raw response
          ;; C-c C-n / C-c C-p - Navigate between requests
          (setq restclient-same-buffer-response t
                restclient-same-buffer-response-name "*HTTP Response*"))

      '' + optionalString cfg.jq.enable ''
        ;; == jq-mode: JSON processing ==
        (use-package jq-mode
          :mode "\\.jq\\'"
          :config
          ;; Interactive jq command
          (global-set-key (kbd "C-c j") 'jq-interactively))

        ;; == restclient-jq: jq integration for restclient ==
        (use-package restclient-jq
          :after restclient
          :config
          ;; Use jq to format JSON responses
          ;; Add :jq .path.to.field to extract specific fields
          )

      '' + optionalString cfg.orgBabel.enable ''
        ;; == ob-restclient: Org-babel REST blocks ==
        (use-package ob-restclient
          :after (org restclient)
          :config
          ;; Enable restclient in org-babel
          (org-babel-do-load-languages
           'org-babel-load-languages
           (append org-babel-load-languages '((restclient . t)))))

        ;; Example org-babel usage:
        ;; #+begin_src restclient
        ;; GET https://api.example.com/users
        ;; Content-Type: application/json
        ;; #+end_src

      '' + ''
        ;; == File associations ==
        ;; .http files are commonly used for REST requests
        (add-to-list 'auto-mode-alist '("\\.rest\\'" . restclient-mode))
      '';
    };
  };
}

