{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.emacs.decknix.lsp;
in
{
  options.programs.emacs.decknix.lsp = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Enable LSP (Language Server Protocol) support via Eglot.
        This provides IDE features like completions, go-to-definition,
        refactoring, and diagnostics for supported languages.
      '';
    };

    # === Language Server Options ===
    kotlin.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Install kotlin-language-server for Kotlin LSP support.";
    };

    java.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable Java LSP support via eglot-java (uses jdt-language-server).";
    };

    nix.enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Install nixd and wire it as the Eglot server for Nix files, so
        flake/home-manager configs get completion, go-to-definition, and
        diagnostics.  nixd resolves flake attrs (unlike the lighter `nil').
      '';
    };

    # === Debug Adapter Protocol ===
    dap.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable DAP (Debug Adapter Protocol) support via dape.";
    };

    # === UI Enhancements ===
    eldocBox.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable eldoc-box for enhanced documentation popups.";
    };
  };

  config = mkIf cfg.enable {
    # Install language servers via Nix
    home.packages = with pkgs;
      (optionals cfg.kotlin.enable [ kotlin-language-server ])
      ++ (optionals cfg.java.enable [ jdt-language-server ])
      ++ (optionals cfg.nix.enable [ nixd ]);

    programs.emacs = {
      extraPackages = epkgs: with epkgs;
        # Eglot is built-in to Emacs 29+, but we ensure it's available.
        # (eglot-java dropped — Java is driven directly via jdtls, see below.)
        [ eglot ]
        ++ (optionals cfg.eldocBox.enable [ eldoc-box ])
        ++ (optionals cfg.dap.enable [ dape ]);

      extraConfig = ''
        ;;; LSP Configuration (Eglot)
        ;;; Generated by decknix - provides IDE features via Language Server Protocol

        ;; == Eglot: Built-in LSP client ==
        (use-package eglot
          :commands (eglot eglot-ensure)
          :hook ((kotlin-mode . eglot-ensure)
                 (kotlin-ts-mode . eglot-ensure)
                 (java-mode . eglot-ensure)
                 (java-ts-mode . eglot-ensure)
                 (nix-mode . eglot-ensure)
                 (nix-ts-mode . eglot-ensure))
          :config
          ;; Performance tuning
          (setq eglot-events-buffer-size 0           ; Disable events buffer for performance
                eglot-autoshutdown t                 ; Shutdown server when last buffer closed
                eglot-sync-connect nil               ; Don't block on connection
                ;; Big monorepos (e.g. upside) make the server resolve a huge
                ;; Gradle classpath during `initialize'; the 30s default is
                ;; far too short and Eglot gives up ("timed out after 30s").
                ;; Allow up to 5 min for the handshake.  Async connect means
                ;; this does not block Emacs — the buffer just isn't
                ;; LSP-managed until the server answers.
                eglot-connect-timeout 300
                eglot-extend-to-xref t)              ; Use LSP for xref

          ;; Keybindings (using C-c l prefix for LSP commands)
          :bind (:map eglot-mode-map
                 ("C-c l r" . eglot-rename)
                 ("C-c l a" . eglot-code-actions)
                 ("C-c l f" . eglot-format)
                 ("C-c l F" . eglot-format-buffer)
                 ("C-c l d" . eldoc)
                 ("C-c l i" . eglot-find-implementation)
                 ("C-c l t" . eglot-find-typeDefinition)
                 ("C-c l h" . eglot-inlay-hints-mode)))

      '' + optionalString cfg.kotlin.enable ''
        ;; == Kotlin Language Server ==
        ;; kotlin-language-server is installed via Nix
        (with-eval-after-load 'eglot
          (add-to-list 'eglot-server-programs
                       '((kotlin-mode kotlin-ts-mode) . ("kotlin-language-server"))))

      '' + optionalString cfg.nix.enable ''
        ;; == Nix Language Server (nixd) ==
        ;; nixd is installed via Nix; resolves flake attrs (unlike `nil').
        (with-eval-after-load 'eglot
          (add-to-list 'eglot-server-programs
                       '((nix-mode nix-ts-mode) . ("nixd"))))

      '' + optionalString cfg.java.enable ''
        ;; == Java Language Server (jdtls, driven directly) ==
        ;; The nix `jdtls' is a Python launcher for eclipse.jdt.ls that speaks
        ;; LSP over stdio and manages its own -data dir, so Eglot drives it
        ;; directly — mirroring the Kotlin setup.  We deliberately do NOT use
        ;; `eglot-java': it expects to locate/download its own jdt.ls bundle
        ;; and never wires the nix `jdtls' into `eglot-server-programs', so
        ;; Eglot silently failed to connect on java-mode buffers (verified on
        ;; the upside monolith).  jdtls imports the Gradle project itself; the
        ;; java-mode `eglot-ensure' hook above starts it.
        (with-eval-after-load 'eglot
          (add-to-list 'eglot-server-programs
                       '((java-mode java-ts-mode) . ("jdtls"))))

      '' + optionalString cfg.eldocBox.enable ''
        ;; == Eldoc-box: Enhanced documentation popups ==
        (use-package eldoc-box
          :hook (eglot-managed-mode . eldoc-box-hover-mode)
          :bind (:map eglot-mode-map
                 ("C-c l k" . eldoc-box-help-at-point))
          :config
          (setq eldoc-box-clear-with-C-g t
                eldoc-box-max-pixel-width 600
                eldoc-box-max-pixel-height 400))

      '' + optionalString cfg.dap.enable ''
        ;; == Dape: Debug Adapter Protocol ==
        (use-package dape
          :commands (dape dape-breakpoint-toggle)
          :bind (("C-c d d" . dape)
                 ("C-c d b" . dape-breakpoint-toggle)
                 ("C-c d B" . dape-breakpoint-remove-all)
                 ("C-c d n" . dape-next)
                 ("C-c d s" . dape-step-in)
                 ("C-c d o" . dape-step-out)
                 ("C-c d c" . dape-continue)
                 ("C-c d r" . dape-restart)
                 ("C-c d q" . dape-quit))
          :config
          ;; Save buffers on startup
          (add-hook 'dape-on-start-hooks (lambda () (save-some-buffers t t)))

          ;; Kotlin debug adapter (kotlin-debug-adapter)
          ;; Note: Requires kotlin-debug-adapter to be installed separately
          (add-to-list 'dape-configs
                       '(kotlin-debug
                         modes (kotlin-mode kotlin-ts-mode)
                         command "kotlin-debug-adapter"
                         :type "kotlin"
                         :request "launch"
                         :mainClass (lambda () (read-string "Main class: "))
                         :projectRoot (lambda () (project-root (project-current t))))))

      '' + ''
        ;; == Completion integration ==
        ;; Eglot integrates with completion-at-point, which Corfu uses
        ;; No additional configuration needed - just works with the completion stack
      '';
    };
  };
}

