{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.decknix.wm.aerospace;

  # Sort workspace keys for consistent ordering
  sortedWorkspaceKeys = sort lessThan (attrNames cfg.workspaces);

  # Build workspace bindings (alt-<key> to switch)
  workspaceBindings = concatMapStringsSep "\n" (key:
    "    alt-${toLower key} = 'workspace ${key}'"
  ) sortedWorkspaceKeys;

  # Build move-to-workspace bindings (alt-shift-<key> to move window)
  moveBindings = concatMapStringsSep "\n" (key:
    "    alt-shift-${toLower key} = 'move-node-to-workspace ${key}'"
  ) sortedWorkspaceKeys;

  # Build persistent workspaces list for TOML
  persistentList = concatMapStringsSep ", " (k: "\"${k}\"") sortedWorkspaceKeys;

  # Build app assignment rules
  appRules = concatMapStringsSep "\n" (rule: ''
    [[on-window-detected]]
        if.app-id = '${rule.appId}'
        run = 'move-node-to-workspace ${rule.workspace}'
  '') cfg.appAssignments;

  # Build monitor assignments from workspaces with monitor set
  monitorAssignments = filterAttrs (k: v: v.monitor != null)
    (mapAttrs (k: v: { inherit (v) monitor; }) cfg.workspaces);

  monitorConfig = optionalString (monitorAssignments != {}) ''
    [workspace-to-monitor-force-assignment]
    ${concatStringsSep "\n" (mapAttrsToList (k: v: "    ${k} = '${v.monitor}'") monitorAssignments)}
  '';

  # Fuzzy picker binding (if enabled)
  fuzzyPickerBinding = optionalString cfg.fuzzyPicker.enable ''
    # Fuzzy workspace picker (requires fzf + choose-gui or terminal)
        ${cfg.fuzzyPicker.key} = '''exec-and-forget ${fuzzyPickerScript}/bin/aero-pick'''
  '';

  # Layout mode bindings (if enabled)
  layoutModeConfig = optionalString cfg.layoutMode.enable ''
    # Layout mode for rapid layout adjustments
    [mode.layout.binding]
        esc = 'mode main'
        # Orientation
        h = ['layout tiles horizontal', 'mode main']
        v = ['layout tiles vertical', 'mode main']
        # Layout type
        t = ['layout tiles horizontal vertical', 'mode main']
        a = ['layout accordion horizontal vertical', 'mode main']
        # Floating/tiling toggle
        f = ['layout floating tiling', 'mode main']
        # Fullscreen
        space = ['fullscreen', 'mode main']
        # Join with neighbors
        left = ['join-with left', 'mode main']
        down = ['join-with down', 'mode main']
        up = ['join-with up', 'mode main']
        right = ['join-with right', 'mode main']
        # Resize (stay in mode for continuous resize)
        minus = 'resize smart -50'
        equal = 'resize smart +50'
        # Balance
        b = ['balance-sizes', 'mode main']
  '';

  # Fuzzy picker script that shows workspace key + name
  fuzzyPickerScript = pkgs.writeShellScriptBin "aero-pick" ''
    #!/usr/bin/env bash
    # Fuzzy workspace picker for AeroSpace
    # Shows: KEY - name (windows count)

    # Build workspace list with names
    workspaces=$(cat <<'EOF'
    ${concatMapStringsSep "\n" (key:
      let ws = cfg.workspaces.${key}; in
      "${key} - ${ws.name}"
    ) sortedWorkspaceKeys}
    EOF
    )

    # Try choose-gui first (macOS native), fallback to fzf in terminal
    if command -v choose &> /dev/null; then
      selected=$(echo "$workspaces" | choose -n 15 -c 00bfff -b 1a1a2e)
    elif command -v fzf &> /dev/null; then
      # Use Alacritty/kitty/Terminal for fzf
      selected=$(echo "$workspaces" | fzf --prompt="Workspace: " --height=15 --reverse)
    else
      # Fallback: just use the first workspace
      echo "No picker available (install choose-gui or fzf)" >&2
      exit 1
    fi

    # Extract workspace key (first word before " - ")
    if [ -n "$selected" ]; then
      ws_key=$(echo "$selected" | cut -d' ' -f1)
      aerospace workspace "$ws_key"
    fi
  '';

  # Main configuration file
  configFile = ''
    # AeroSpace Configuration - Generated by decknix
    # See: https://nikitabobko.github.io/AeroSpace/guide
    #
    # Quick reference:
    #   alt-h/j/k/l     Navigate windows
    #   alt-shift-h/j/k/l  Move windows
    #   alt-<key>       Switch to workspace
    #   alt-shift-<key> Move window to workspace
    #   alt-space       Fuzzy workspace picker
    #   alt-/           Toggle tiles layout
    #   alt-,           Toggle accordion layout
    #   alt-tab         Switch to previous workspace
    #   alt-;           Enter layout mode

    config-version = 2
    start-at-login = ${boolToString cfg.startAtLogin}

    # Normalizations for predictable tiling
    enable-normalization-flatten-containers = true
    enable-normalization-opposite-orientation-for-nested-containers = true

    # Layout settings
    accordion-padding = 30
    default-root-container-layout = 'tiles'
    default-root-container-orientation = 'auto'

    # Mouse follows focused monitor (i3 default behavior)
    on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

    # Persistent workspaces (always available in workspace list)
    persistent-workspaces = [${persistentList}]

    [key-mapping]
        preset = 'qwerty'

    # Gaps between windows
    [gaps]
        inner.horizontal = ${toString cfg.gaps.inner}
        inner.vertical = ${toString cfg.gaps.inner}
        outer.left = ${toString cfg.gaps.outer}
        outer.bottom = ${toString cfg.gaps.outer}
        outer.top = ${toString cfg.gaps.outer}
        outer.right = ${toString cfg.gaps.outer}

    ${monitorConfig}

    # App-to-workspace assignments
    ${appRules}

    # Main binding mode
    [mode.main.binding]

    # === Navigation (vim-style) ===
        alt-h = 'focus left'
        alt-j = 'focus down'
        alt-k = 'focus up'
        alt-l = 'focus right'

    # === Move windows ===
        alt-shift-h = 'move left'
        alt-shift-j = 'move down'
        alt-shift-k = 'move up'
        alt-shift-l = 'move right'

    # === Layout quick toggles ===
        alt-slash = 'layout tiles horizontal vertical'
        alt-comma = 'layout accordion horizontal vertical'
        alt-f = 'fullscreen'
        alt-shift-f = 'layout floating tiling'

    # === Resize ===
        alt-minus = 'resize smart -50'
        alt-equal = 'resize smart +50'

    # === Workspace switching ===
    ${workspaceBindings}

    # === Move window to workspace ===
    ${moveBindings}

    # === Monitor navigation ===
        alt-tab = 'workspace-back-and-forth'
        alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
        # Focus monitor by direction
        alt-ctrl-h = 'focus-monitor left'
        alt-ctrl-l = 'focus-monitor right'
        alt-ctrl-j = 'focus-monitor down'
        alt-ctrl-k = 'focus-monitor up'

    # === Enter layout mode for advanced layout operations ===
        alt-semicolon = 'mode layout'

    ${fuzzyPickerBinding}

    ${layoutModeConfig}

    # Service mode for destructive operations
    [mode.service.binding]
        esc = 'mode main'
        r = ['flatten-workspace-tree', 'mode main']
        backspace = ['close-all-windows-but-current', 'mode main']

    ${cfg.extraConfig}
  '';

in {
  config = mkIf cfg.enable {
    # Write the aerospace config file
    xdg.configFile."aerospace/aerospace.toml".text = configFile;

    # Add fuzzy picker script to path
    home.packages = mkIf cfg.fuzzyPicker.enable [
      fuzzyPickerScript
      pkgs.fzf  # Ensure fzf is available as fallback
    ];

    # Add helpful shell aliases
    programs.zsh.shellAliases = mkIf config.programs.zsh.enable {
      aero = "aerospace";
      aerols = "aerospace list-workspaces --all";
      aerowin = "aerospace list-windows --all";
      aeropick = "aero-pick";
    };
  };
}

