{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.decknix.cli.extensions;

  # Type definition for extensions
  extensionType = types.submodule {
    options = {
      description = mkOption { type = types.str; };
      command = mkOption { type = types.str; };
    };
  };

  extensionNames = builtins.attrNames cfg;

  # Build the completion entries for extensions
  extensionCompletions = concatMapStringsSep "\n" (name:
    let desc = cfg.${name}.description;
    in "    '${name}:${desc}'"
  ) extensionNames;

  # Generate zsh completion script covering built-in + extension subcommands
  completionScript = pkgs.writeTextDir "share/zsh/site-functions/_decknix" ''
    #compdef decknix

    # Auto-generated by decknix Nix module — do not edit manually.

    _decknix() {
      local -a commands
      commands=(
        'switch:Switch system configuration'
        'update:Update flake inputs'
        'help:Show help for a command'
    ${extensionCompletions}
      )

      _arguments -C \
        '1:command:->cmd' \
        '*::arg:->args'

      case "$state" in
        cmd)
          _describe -t commands 'decknix command' commands
          ;;
        args)
          case "$words[1]" in
            switch)
              _arguments \
                '--dry-run[Build only — do not activate]' \
                '--dev[Use local framework checkout (~/tools/decknix)]' \
                '--dev-path[Explicit path to local framework]:path:_directories'
              ;;
            update)
              _arguments '1:input:(decknix)'
              ;;
            help)
              local -a help_cmds
              help_cmds=(switch update ${concatStringsSep " " extensionNames})
              _describe -t commands 'subcommand' help_cmds
              ;;
            *)
              # Extension subcommands — fall back to file completion
              _files
              ;;
          esac
          ;;
      esac
    }

    _decknix "$@"
  '';

in {
  options.decknix.cli.extensions = mkOption {
    type = types.attrsOf extensionType;
    default = {};
    description = ''
      Home-manager level extensions for the decknix CLI.
      Each extension becomes both a `decknix <name>` subcommand
      and gets shell completions.
    '';
    example = {
      board = {
        description = "Issue dashboard across repos";
        command = "/nix/store/.../bin/decknix-board";
      };
    };
  };

  config = mkIf (cfg != {}) {
    # 1. Install zsh completions (includes built-in + extension commands)
    home.packages = [ completionScript ];

    # 2. Generate home-level extensions.json for the Rust binary
    home.file.".config/decknix/extensions.json".text = builtins.toJSON (
      mapAttrs (n: v: { inherit (v) description command; }) cfg
    );
  };
}

