use clap::{Parser, Subcommand, Args, CommandFactory, FromArgMatches};
use serde::Deserialize;
use std::collections::HashMap;
use std::process::Command;
use std::fs;

// 1. Static Core Commands
#[derive(Parser)]
#[command(name = "decknix")]
#[command(about = "The Decknix Framework CLI", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Update flake inputs
    Update {
        /// Specific input to update
        input: Option<String>,
    },
    /// Switch system configuration
    Switch {
        #[arg(long)]
        dry_run: bool,
    },
    // This variant catches unknown commands to check extensions
    #[command(external_subcommand)]
    External(Vec<String>),
}

// 2. Dynamic Configuration Schema
#[derive(Deserialize, Debug, Clone)]
struct ExtensionConfig {
    description: String,
    command: String, // Path to script or executable
}

type ExtensionMap = HashMap<String, ExtensionConfig>;

fn main() -> anyhow::Result<()> {
    // A. Load Extensions from JSON (generated by Nix)
    let config_path = dirs::home_dir()
        .unwrap()
        .join(".config/decknix/extensions.json");

    let extensions: ExtensionMap = if config_path.exists() {
        let file = fs::File::open(config_path)?;
        serde_json::from_reader(file)?
    } else {
        HashMap::new()
    };

    // B. Parse Args
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::Switch { dry_run }) => {
            println!("🔄 Switching...");
            // Call darwin-rebuild...
        }
        Some(Commands::Update { input }) => {
            println!("⬇️ Updating...");
            // Call nix flake update...
        }
        Some(Commands::External(args)) => {
            // C. Handle Dynamic Commands
            let cmd_name = &args[0];
            if let Some(ext) = extensions.get(cmd_name) {
                println!("Running extension: {}", cmd_name);
                // Execute the command defined in JSON
                let status = Command::new("sh")
                    .arg("-c")
                    .arg(&ext.command)
                    .status()?;
                std::process::exit(status.code().unwrap_or(1));
            } else {
                eprintln!("Unknown command: {}", cmd_name);
            }
        }
        None => {
            // Print help if no args
            Cli::command().print_help()?;
        }
    }
    Ok(())
}
